services:
  - type: web
    name: wger-backend
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python manage.py migrate
      python manage.py collectstatic --noinput
    startCommand: gunicorn wsgi:application
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: wger-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true

databases:
  - name: wger-db
